### ISSUE TITLE
Issues with M365SAT v2.0rc

### ISSUE THREAD

**Issue by asterictnl-lvdw** [CompliantSec/M365SAT#14]
1-8-2023: 13:00
We are aware that there are some issues with the following things:
- There are some HTML Reporting structure issues.
- Issues with Exchange CMDLets containing the new EXO Commands when they are ran after some commands
I will push some fixes to GitHub when I am aware that things have been fixed.
1-8-2023: 13:05
- Microsoft Exchange CMDLets seem to work when the affected CMDLets are ran standalone or without the other CMDLets before I will investigate in this week which ExchangeCMDlets are affected.
2-8-2023: 10:15
- Investigation shows that the problem was not existing in the ExchangeCmdlet. Since the Azure cmdlets are ran before this, there might be something in there that is causing issues with the EXO cmdlets. The Az and MicrosoftGraph cmdlets have been updated to their latest version to see if that resolves the issue. 
2-8-2023: 10:30
- It seems that the CSTM is not affected as well. This might mean that the problem is in the main Az cmdlets. This will be investigated to see what the problem is.
2-8-2023: 12:00
- It seems to be an issue with the authentication schema. The error is caused by human error. The advice is to not close the localhost tabs in Powershell 7 until the audit is done. It seems that background jobs in Powershell 7 depend sometimes onto these tabls. If you close the some tabs too early, the authentication schema will hang and result into failing to authenticate. The same is very important for the Security & Compliance Schema. If this tab is closed too early the EXO commands will not work as the files are not dumped entirely in the TEMP folder on Windows. 
- In the latest version CISAz300.ps1 has an issue with a assembly conflict as a different assembly containing the same command has already been loaded. This is an issue with AzAccount itself. 
2-8-2023: 15:00
- Finally I can conclude that there is only a problem with CISAz300.ps1 which has an assembly conflict with a different assembly within the same Az package. the EXO cmdlets are working fine now on PowerShell 7 as long you keep the localhost tabs on, because once you close them they cannot make the connection anymore thus failing the commands. Keep in mind to keep all the localhost tabs on until the whole audit has been completed. The issue with CISAz300 will fixed soon, changing it to a different mechanism.

~LvdW

**Comment by asterictnl-lvdw** [comment]
When something gets updated and is available for external testing. Please download from the **dev** branch. So you are able to test it as well. I will make new branches soon for alpha releases that will be more frequently pushed to.

**Comment by asterictnl-lvdw** [comment]
4-8-2023 18:15
- CISMAz210.ps1 gives an error at some tenant. I am looking into this issue and provide a fix in Alpha when possible. This is scheduled for next week Monday. 
- There has been an quick fix released in the Alpha Branch regarding CISAz300.ps1 due to an issue with the validation mechanism. It should now work as expected as I have changed it to the Invoke mechanism instead.

**Comment by asterictnl-lvdw** [comment]
31-8-2023 23:45
- I have found issues with Inspector CISMAz210.ps1 encountering an error where the response code will return a Bad Request. This will be fixed in the next upcoming release.
- We have found issues with CISMEx120 which is very slow at running when you have a lot of emailaddresses. This will be investigated and a quick-fix will be in place once ready
- I have encountered an issue with CSTM-Ex024 where a unknown parsing error occured with Newtonsoft.Json failing to parse correctly. This will be investigated and a quick-fix will be in place once ready
- A null value was being tried to be divided by 0 in the alpha release sometimes resulting into an incorrect report. 
The new release is scheduled between 1 sept. 2023 and 8 sept. 2023

~LvdW

**Comment by karimzaki** [comment]
sharepoint Module is always f=giving error i m using powershell installed from micorosf store if this helps in troubleshooting

**Comment by asterictnl-lvdw** [comment]
@karimzaki ,

Thank you for submission. Have you tried to use the standalone version and the PowerShell 5 version?

You can download the latest version of PowerShell 7 here: https://github.com/PowerShell/PowerShell/releases/tag/v7.3.6

I will need to see if I can reproduce the issue. Could you please write down the steps below what you are actually doing and the screenshot of the actual error so I can check it for you what the actual problem is.

Thank you.

~LvdW

**Comment by asterictnl-lvdw** [comment]
v2.1 has been released. This issue will be solved for now. When there are any issues with v2.1 a new issue will be raised.

~LvdW
