### ISSUE TITLE
M365SAT execution for different Audits / E3/E5 Licenses?

### ISSUE THREAD

**Issue by PS-Tron** [CompliantSec/M365SAT#27]
Hello, is it somehow possible to run the audit, so I can specifiy which audits are run, according to the audited M365 environement?
(E3 Level 1, E3 Level 2, E5 Level 1, E5 Level 2)

**Comment by asterictnl-lvdw** [comment]
Good morning @PS-Tron ,

Thank you for submitting the issue. No I did not do that yet, but I will submit this as a user story for me and hopefully I can release it in the next release. I will add the following things:
- A tag to determine which license it applies to
- Validation / Parameters so only the respective inspectors will be used.

Again thank you for your submission.

I will keep this post updated if anything changes. You are very welcome to test it on the alpha branch once it is released there.

~LvdW

**Comment by asterictnl-lvdw** [comment]
Hello @PS-Tron ,

I am implementing your idea in v2.2 in the next upcoming release. There I will add some features regarding different audits.

How the concept will be is for later decision.

~LvdW

**Comment by asterictnl-lvdw** [comment]
Hello @PS-Tron , the feature you requested is available in release v2.2. This will be released this afternoon around 5pm GMT+1

If you would like you can test it out. There are example commands in the M365SATTester powershell script.

~LvdW

**Comment by asterictnl-lvdw** [comment]
I will close this issue. I have released it for the public in the production branch. Feel free to test it out. If you encounter issues, let me know and I will look into it. 

~LvdW
