### ISSUE TITLE
Get-M365SATReport cmd seems to fail when query, but running M365SATester.ps1 itself is fine.

### ISSUE THREAD

**Issue by Leectan** [CompliantSec/M365SAT#38]
<img width="1141" alt="Windows_11_64-bit_Arm" src="https://github.com/asterictnl-lvdw/M365SAT/assets/24819052/afe57b76-43ea-429b-96f1-a5306a28e448">

Also, looks like M365SATTester.ps1 file itself doesn't call the CIS v3.1.0 Level 2 checks. Could you confirm that? Thank you

**Comment by asterictnl-lvdw** [comment]
Hi @Leectan ,

I will look into this. Give me a bit of time to see if this can be fixed to see if I can reproduce this issue. 

Just to verify you are running the M365SATTester.ps1 and changed the values there so you can execute it normally?

~LvdW

PS: Also about your updating modules, I am aware that the update script might not work sometimes as expected. This is a known bug. The best thing to do here is to manually update the modules to make sure you stay up-to-date with the latest powershell cmdlets. PowerShell is a bit iffy on the module update and comparing older modules within the available respositories.

**Comment by asterictnl-lvdw** [comment]
To determine if it works for you as well, please run the following commands:
`Get-M365SATReport -OutPath "C:\Out" -Username "yourname@contoso.com" -EnvironmentType M365 -BenchmarkVersion "Latest" -Modules "All" -LicenseMode "E3" -LicenseLevel "L2" -reportType "HTML" -AllowLogging "Warning" -LocalMode -SkipChecks`

Please keep in mind if you only audit Pure Azure that it audits CIS21 of Azure parts as well which could overlap with the Microsoft 365 benchmark as well. 

Please let me know the results.

**Comment by RFarnellEq** [comment]
When I ran the above query, I get the following:
![image](https://github.com/user-attachments/assets/22103c51-f1a9-47ad-89f0-7df55ac949ec)

**Comment by RFarnellEq** [comment]
The main.zip or the folders to it, seem to be missing https://github.com/asterictnl-lvdw/M365SAT-inspectors/archive/refs/heads/main.zip

**Comment by asterictnl-lvdw** [comment]
I have made a change to the update and removal of old versions mechanism. It is always recommended to install them manually first and use the M365SAT Tester to execute it. @Leectan 

Maybe you can test the update and removal script for me to see if it updates correctly now. If you get errors that modules are in use, please kindly fully close powershell and end powershell from the task manager and open a new session and run the modules or the script that is prompted within the warning message to fully delete the old version.

~LvdW

**Comment by asterictnl-lvdw** [comment]
@Leectan , 

Please test the update-module for me by removing the `-SkipChecks` parameter at the 2nd command in the `M365SATTester.ps1` script to check if it is working as expected.

Thank you.

~LvdW

**Comment by asterictnl-lvdw** [comment]
This has been fixed in the v2.3 release. If the problem still exists, please re-open the issue.
