### ISSUE TITLE
CISMAz5111 - Wrong expected value?

### ISSUE THREAD

**Issue by M0nk3yOo** [CompliantSec/M365SAT#45]
Dear @asterictnl-lvdw 

we think we've a litte mistake in CISMAz5111 (?)

We've the opinion, that the expected value should be $false, because it's a negation. The result cmdlet is "isEnabled". From our understanding has a result of $false if the setting is disabled (and that's what CIS expects)

<img width="811" alt="image" src="https://github.com/user-attachments/assets/34f26e3d-2f11-41f9-b4d1-e6d3f30ccd12">

What do you think?

<img width="406" alt="image" src="https://github.com/user-attachments/assets/e0867c7f-164d-4cc7-a2fb-b8495da160cd">

Best
M0nk3y

**Comment by asterictnl-lvdw** [comment]
Hi @M0nk3yOo ,

Thank you for your submission. This whole 5.1.1.1 thing is very contradicting in comparison towards the other security measures. What the CIS actually wants is that you first enable Secure Defaults to have the Secure Defaults firstly enabled and then disable it and go further with the implementation.

But indeed what you say is right. I have fixed it and will do a quick release towards production for this.

I will close this issue.

~LvdW
